name: Feature Request
description: Suggest a new feature or enhancement for CodeMie CLI
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have read the [documentation](https://github.com/codemie-ai/codemie-code#readme)
          required: true
        - label: This is a feature request, not a bug report
          required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area does this feature relate to?
      options:
        - CLI Commands
        - Agent System (plugins, registry)
        - Configuration & Profiles
        - Analytics & Tracking
        - Authentication & SSO
        - CI/CD Workflows
        - Built-in Agent (CodeMie Native)
        - External Agents (Claude, Gemini)
        - Proxy Server
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What is the current limitation?
      placeholder: |
        Currently, when I try to..., I have to...
        This is problematic because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or enhancement
      placeholder: |
        I would like to be able to...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case or workflow that would benefit from this feature
      placeholder: |
        In my daily workflow, I...
        This feature would help me...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Example Usage
      description: Show examples of how you envision using this feature
      placeholder: |
        ```bash
        codemie new-command --option value
        ```
      render: bash
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor convenience
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      options:
        - label: I would be willing to implement this feature and submit a PR
          required: false
        - label: I would be willing to help test this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        Related features in other tools:
        - Tool X does this by...

        Mockups or diagrams:
        (attach images if helpful)
    validations:
      required: false
